[settings]
spaceapi_url = "https://vloer.ko-lab.space/spaceapi.json"

[messages]
space_open = "The Space is open :partying_face:"
space_closed = "The Space is closed :scream:"

[statuses]
change_status = true
space_open = "an open Space 😀"
space_closed = "a closed Space 😱"